### ISSUE TITLE
Boarding fails to add new tester

### ISSUE THREAD

**Issue by afehners** [fastlane/boarding#137] opened 2017-04-26 16:18 UTC
Probably related to the recent TestFlight changes, but after updating to the latest version of Boarding I am unable to add a new tester. Heroku logs extract:

> 2017-04-26T16:14:44.122407+00:00 app[web.1]: Started POST "/submit" for 94.193.104.4 at 2017-04-26 16:14:44 +0000
> 2017-04-26T16:14:44.123607+00:00 app[web.1]: Processing by InviteController#submit as HTML
> 2017-04-26T16:14:44.123673+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"***************************", "first_name"=>"bob", "last_name"=>"bill", "email"=>"************@gmail.com", "token"=>"**********", "commit"=>"Get Beta Access"}
> 2017-04-26T16:14:44.124957+00:00 app[web.1]:   Rendered invite/index.html.erb within layouts/application (0.2ms)
> 2017-04-26T16:14:44.126252+00:00 app[web.1]: Completed 200 OK in 2ms (Views: 1.9ms)
> 2017-04-26T16:14:49.834437+00:00 app[web.1]: Started POST "/submit" for 94.193.104.4 at 2017-04-26 16:14:49 +0000
> 2017-04-26T16:14:49.843058+00:00 app[web.1]: Processing by InviteController#submit as HTML
> 2017-04-26T16:14:49.843341+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"****************************", "first_name"=>"bob", "last_name"=>"bill", "email"=>"**********@gmail.com", "token"=>"**************", "commit"=>"Get Beta Access"}
> 2017-04-26T16:14:49.862455+00:00 app[web.1]: Going to create a new tester: ***********@gmail.com - bob bill
> 2017-04-26T16:14:53.768764+00:00 app[web.1]: Found tester 
> 2017-04-26T16:14:54.007883+00:00 app[web.1]: #<Spaceship::Client::InsufficientPermissions: User *******@*********.com (Team ID *******) doesn't have enough permission for the following action: parse_response>
> 2017-04-26T16:14:54.008110+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/client.rb:574:in `raise_insuffient_permission_error!'
> 2017-04-26T16:14:54.008111+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/client.rb:549:in `detect_most_common_errors_and_raise_exceptions'

**Comment by taquitos** [comment] 2017-04-26 18:05
Give it one more shot, I just merged a large PR with updates for the recent changes. That being said, this error message does sort of seem like your itunesconnect user doesn't have the right role to be able to add external testers... or our error message is wrong 🤷‍♂️

**Comment by Lida** [comment] 2017-04-26 19:29
The Gemfile.lock shows Fastlane version 2.29.1?

**Comment by taquitos** [comment] 2017-04-26 19:47
> The Gemfile.lock shows Fastlane version 2.29.1?

Whoops, I had a local version of fastlane where I bumped the version up super high. The current version of fastlane is correct. I'll fix that.

**Comment by Lida** [comment] 2017-04-26 19:52
Cool. I also added a couple of notes on the issues I had when I ran latest in your last commit.

**Comment by taquitos** [comment] 2017-04-26 19:57
Fixed the version (back to 2.28.4)

**Comment by mrgrauel** [comment] 2017-04-27 05:21
I have the same issue with the current master version of boarding. Deployed on Heroku and the user has the permission to add testers.

**Comment by afehners** [comment] 2017-04-27 10:34
Pulled latest changes and pushed to my heroku app. I get the same failure.

Permission of user credentials supplied is "App Manager", which is able to add new testers. 
It's strange that the error is that the user does not have permission to 'parse_response'. It's usual for permissions to stop an action being taken, but not to read a response from an action?

#<Spaceship::Client::InsufficientPermissions: User ********@*********.com (Team ID ******) doesn't have enough permission for the following action: parse_response>

**Comment by taquitos** [comment] 2017-04-27 17:04
Yeah, I think that's misleading. What seems to be happening is that during `parse_response` spaceship isn't getting the content it is expecting and it raises an exception via: `detect_most_common_errors_and_raise_exceptions` because `if body["messages"] && body["messages"]["error"].include?("Forbidden")` is true.
So basically some call is returning that your user doesn't have permission. 

It looks like Spaceship makes a call to: `https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/users/pre/ext`
and that call returns 
```{
	"data": null,
	"messages": {
		"warn": null,
		"info": null,
		"error": ["Forbidden"]
	},
	"statusCode": "ERROR"
}```
when your account only has "App Manager".

I confirmed by changing the role from "App Manager" to "Admin" and restarting my boarding instance.

**Comment by taquitos** [comment] 2017-04-27 17:08
Just added fastlane issue: https://github.com/fastlane/fastlane/issues/9011

**Comment by mrgrauel** [comment] 2017-05-09 09:04
@taquitos something new?

**Comment by taquitos** [comment] 2017-05-09 15:37
@mrgrauel  I'm writing some tests right now for: https://github.com/fastlane/fastlane/pull/9046 and that should fix this.

**Comment by mrgrauel** [comment] 2017-05-09 18:47
Awesome. Can I help you?

**Comment by taquitos** [comment] 2017-05-09 20:33
Thanks for the offer! I'm actually now just waiting for feedback from 2 people, and then we're 💯

**Comment by JAStanton** [comment] 2017-05-10 00:08
Oh it looks like https://github.com/fastlane/fastlane/pull/9046 was just merged, what needs to happen to get boarding project to pull in the fix?

**Comment by taquitos** [comment] 2017-05-10 00:19
Changes were merged into fastlane that this depends on now. I needed to make a few updates to boarding, so I have https://github.com/fastlane/boarding/pull/150 up.
It copies a bit of the logic found in the fastlane pr, so maybe we should extract out the duplicate logic into Spaceship at some point. I wanted to get us back up and running instead spending the time refactoring.

Hopefully we can do a new fastlane release soon. In the meantime, you can try this branch against fastlane master.

**Comment by taquitos** [comment] 2017-05-19 18:45
This has shipped 🎉

**Closed by taquitos** 2017-05-19 18:45 UTC
