### ISSUE TITLE
ITC Api Change

### ISSUE THREAD

**Issue by davoda** [fastlane/boarding#84] opened 2016-06-24 01:07 UTC
"Something went wrong, please contact the application owner" is back.

Constantly returning the following error now:
`#<Spaceship::Client::UnexpectedResponse: {
"data"=>nil, 
"messages"=>{"warn"=>nil, "info"=>nil, "error"=>["service_http_bad_response"]}, "statusCode"=>"ERROR"}>`

**Comment by KrauseFx** [comment] 2016-06-24 01:18
Unfortunately that's an error on Apple's side, duplicate of https://github.com/fastlane/fastlane/issues/5200

Please also contact Apple by sending a support request or calling them. 

This is not a fastlane error, the same thing happens when you try to add an external tester using iTunes Connect

**Comment by davoda** [comment] 2016-06-24 02:43
@KrauseFx I was able to add users on their site before. But yes, Pilot is also down :(

**Comment by KrauseFx** [comment] 2016-06-24 17:48
@davoda What happens if you follow these steps? https://github.com/fastlane/fastlane/issues/5200#issuecomment-228186725

**Comment by pbeast** [comment] 2016-06-26 10:16
Hi, 
I have the same probelm `(#<Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["service_http_bad_response"]}, "statusCode"=>"ERROR"}>)`, but **can** create user manually using iTunesConnect. 

Can I help somehow?

**Comment by KrauseFx** [comment] 2016-06-27 04:43
@pbeast Creating external testers? Or internal ones?

**Comment by pbeast** [comment] 2016-06-27 05:42
@KrauseFx, externals

**Comment by KrauseFx** [comment] 2016-06-27 10:18
@pbeast I just tried, it's not working for me

**Comment by pbeast** [comment] 2016-06-27 11:03
@KrauseFx , hmmm. Very strange. Will check again

**Comment by samwize** [comment] 2016-06-28 01:31
Seems like Apple fixed on their side. Adding External testers on ITC works now.

Boarding works without error too.

**Comment by KrauseFx** [comment] 2016-06-28 09:04
I just tried both boarding and pilot, and both work without problems. I'll close this issue for now, however feel free to re-open if you're still running into issues 👍

**Closed by KrauseFx** 2016-06-28 09:04 UTC

**Comment by pbeast** [comment] 2016-06-28 14:30
Thanks a lot
