### ISSUE TITLE
Fatal Sign-up Error ("Undefined method 'admin?' for nil:NilClass")

### ISSUE THREAD

**Issue by RPasecky** [fastlane/boarding#156] opened 2017-05-15 01:51 UTC
I have successfully deployed the heroku app however when I try to create a new user, I get this error 

> "Something went wrong, please contact the application owner: undefined method `admin?' for nil:NilClass"

Has anyone else run into this issue?

This is the log from the event, with some redacting: 

> 2017-05-15T01:45:04.170327+00:00 heroku[router]: at=info method=GET path="/assets/application-895ae8ca2b3268d6153266e6779a6d89796096e2da27247f1558a72aa570cff9.css" host=sleepy-brushlands-18802.herokuapp.com request_id=5f8e3154-6abd-45ac-85aa-f4f29367e317 fwd="107.77.211.168" dyno=web.1 connect=0ms service=1ms status=304 bytes=48 protocol=https
2017-05-15T01:45:04.372172+00:00 heroku[router]: at=info method=GET path="/assets/application-3242170f28b3708d4591ea0b3f7ddfc4e4c9c6e182222d74f01449e323a3dbb7.js" host=sleepy-brushlands-18802.herokuapp.com request_id=b00c459c-2ec3-4f0a-9918-581b7023e7f7 fwd="107.77.211.168" dyno=web.1 connect=0ms service=1ms status=304 bytes=48 protocol=https
2017-05-15T01:45:04.363907+00:00 heroku[router]: at=info method=GET path="/assets/application-895ae8ca2b3268d6153266e6779a6d89796096e2da27247f1558a72aa570cff9.css" host=sleepy-brushlands-18802.herokuapp.com request_id=bcd6e6c8-97e0-4c0a-be81-cf3a82b178cf fwd="107.77.211.168" dyno=web.1 connect=0ms service=5ms status=304 bytes=48 protocol=https
2017-05-15T01:45:04.552287+00:00 heroku[router]: at=info method=GET path="/assets/application-3242170f28b3708d4591ea0b3f7ddfc4e4c9c6e182222d74f01449e323a3dbb7.js" host=sleepy-brushlands-18802.herokuapp.com request_id=e9754802-5568-47d7-b073-f0033ca09942 fwd="107.77.211.168" dyno=web.1 connect=0ms service=1ms status=304 bytes=48 protocol=https
2017-05-15T01:45:07.762504+00:00 heroku[router]: at=info method=GET path="/" host=sleepy-brushlands-18802.herokuapp.com request_id=5a7eff58-4823-499b-96d1-63a915a192a0 fwd="107.77.211.168" dyno=web.1 connect=4ms service=6ms status=200 bytes=3119 protocol=https
2017-05-15T01:45:07.757606+00:00 app[web.1]: Started GET "/" for 107.77.211.168 at 2017-05-15 01:45:07 +0000
2017-05-15T01:45:07.758383+00:00 app[web.1]: Processing by InviteController#index as HTML
2017-05-15T01:45:07.760849+00:00 app[web.1]:   Rendered invite/index.html.erb within layouts/application (1.8ms)
2017-05-15T01:45:07.761373+00:00 app[web.1]: Completed 200 OK in 3ms (Views: 2.5ms)
2017-05-15T01:46:06.790195+00:00 app[web.1]: Started POST "/submit" for 107.77.211.168 at 2017-05-15 01:46:06 +0000
2017-05-15T01:46:06.791171+00:00 app[web.1]: Processing by InviteController#submit as HTML
2017-05-15T01:46:06.791247+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"CeQOOGGubrL6AdIFaYz8y3nKMNTnxYqfDxaESAXEJqha32BA9hXYwcwxW/9R6xlOef+N2hNmKExQ6ex3KnN45A==", "first_name"=>"First Name", "last_name"=>"Last Name", "email"=>"we*********@gmail.com", "token"=>"Spring*******", "commit"=>"Get Beta Access"}
2017-05-15T01:46:06.792077+00:00 app[web.1]: Creating a new tester: weg********@gmail.com ******
2017-05-15T01:46:07.667984+00:00 heroku[router]: at=info method=POST path="/submit" host=sleepy-brushlands-18802.herokuapp.com request_id=c25fadbc-7977-468b-922b-bda034bad703 fwd="107.77.211.168" dyno=web.1 connect=9ms service=1001ms status=200 bytes=2099 protocol=https
2017-05-15T01:46:07.662244+00:00 app[web.1]: #<NoMethodError: undefined method `admin?' for nil:NilClass>
2017-05-15T01:46:07.663545+00:00 app[web.1]: /app/app/services/boarding_service.rb:111:in `find_app_tester'
2017-05-15T01:46:07.663546+00:00 app[web.1]: /app/app/services/boarding_service.rb:42:in `add_tester'
2017-05-15T01:46:07.663548+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:91:in `create_and_add_tester'
2017-05-15T01:46:07.663548+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:74:in `submit'
2017-05-15T01:46:07.663549+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2017-05-15T01:46:07.663550+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
2017-05-15T01:46:07.663551+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
2017-05-15T01:46:07.663552+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2017-05-15T01:46:07.663552+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
2017-05-15T01:46:07.663553+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
2017-05-15T01:46:07.663554+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
2017-05-15T01:46:07.663554+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
2017-05-15T01:46:07.663555+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
2017-05-15T01:46:07.663556+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
2017-05-15T01:46:07.663557+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
2017-05-15T01:46:07.663557+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
2017-05-15T01:46:07.663572+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2017-05-15T01:46:07.663573+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
2017-05-15T01:46:07.663574+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2017-05-15T01:46:07.663575+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
2017-05-15T01:46:07.663575+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2017-05-15T01:46:07.663576+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2017-05-15T01:46:07.663577+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
2017-05-15T01:46:07.663577+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
2017-05-15T01:46:07.663578+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
2017-05-15T01:46:07.663579+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2017-05-15T01:46:07.663580+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
2017-05-15T01:46:07.663580+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
2017-05-15T01:46:07.663581+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
2017-05-15T01:46:07.663582+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2017-05-15T01:46:07.663582+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
2017-05-15T01:46:07.663583+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
2017-05-15T01:46:07.663584+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
2017-05-15T01:46:07.663584+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call'
2017-05-15T01:46:07.663585+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
2017-05-15T01:46:07.663586+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:38:in `call'
2017-05-15T01:46:07.663587+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
2017-05-15T01:46:07.663588+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2017-05-15T01:46:07.663588+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
2017-05-15T01:46:07.663785+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
2017-05-15T01:46:07.663786+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
2017-05-15T01:46:07.663787+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2017-05-15T01:46:07.663788+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2017-05-15T01:46:07.663788+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
2017-05-15T01:46:07.663789+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
2017-05-15T01:46:07.663790+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
2017-05-15T01:46:07.663790+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2017-05-15T01:46:07.663791+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2017-05-15T01:46:07.663792+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2017-05-15T01:46:07.663792+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2017-05-15T01:46:07.663793+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
2017-05-15T01:46:07.663794+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
2017-05-15T01:46:07.663794+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2017-05-15T01:46:07.663795+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-05-15T01:46:07.663796+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
2017-05-15T01:46:07.663796+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
2017-05-15T01:46:07.663797+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2017-05-15T01:46:07.663798+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
2017-05-15T01:46:07.663799+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
2017-05-15T01:46:07.663799+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2017-05-15T01:46:07.663800+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
2017-05-15T01:46:07.663801+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
2017-05-15T01:46:07.663802+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
2017-05-15T01:46:07.663805+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
2017-05-15T01:46:07.663806+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
2017-05-15T01:46:07.663807+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
2017-05-15T01:46:07.663808+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
2017-05-15T01:46:07.663808+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
2017-05-15T01:46:07.663809+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2017-05-15T01:46:07.665578+00:00 app[web.1]:   Rendered invite/index.html.erb within layouts/application (0.5ms)
2017-05-15T01:46:07.668096+00:00 app[web.1]: Completed 200 OK in 877ms (Views: 3.8ms)
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-05-15T01:46:07.663801+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
2017-05-15T01:46:07.663800+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
2017-05-15T01:46:07.663802+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
2017-05-15T01:46:07.663805+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
2017-05-15T01:46:07.663806+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
2017-05-15T01:46:07.663807+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
2017-05-15T01:46:07.663808+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
2017-05-15T01:46:07.663808+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
2017-05-15T01:46:07.663809+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2017-05-15T01:46:07.665578+00:00 app[web.1]:   Rendered invite/index.html.erb within layouts/application (0.5ms)
2017-05-15T01:46:07.668096+00:00 app[web.1]: Completed 200 OK in 877ms (Views: 3.8ms)

**Comment by RPasecky** [comment] 2017-05-15 03:24
Did some testing after looking at the source code and it looks like its related to these lines in boarding_service.rb:

`  private

    def create_tester(email: nil, first_name: nil, last_name: nil, app: nil)
      current_user = Spaceship::Members.find(Spaceship::Tunes.client.user)
      if current_user.admin?
        tester = Spaceship::Tunes::Tester::External.create!(email: email,
                                                       first_name: first_name,
                                                        last_name: last_name)
        Rails.logger.info "Successfully added tester: #{email} to your account"
      elsif current_user.app_manager?

        Spaceship::TestFlight::Tester.create_app_level_tester(app_id: app.apple_id,
                                                          first_name: first_name,
                                                           last_name: last_name,
                                                               email: email)
        tester = Spaceship::Tunes::Tester::External.find_by_app(app.apple_id, email)
        Rails.logger.info "Successfully added tester: #{email} to app: #{app.name}"
      else
        raise "Current account doesn't have permission to create a tester"
      end`


I created another itunes connect account that was only an 'App Manager' and I was able to create users. It seems like 'boarding' doesn't like me using my admin account for some reason when I deploy the heroku app. Any suggestions?

**Comment by eskerber** [comment] 2017-06-23 13:02
I second this 👋 

Though I get _other_ errors when using a non-admin (app manager).

**Comment by taquitos** [comment] 2017-06-26 22:40
Thanks for the report, being an `admin` should work. In this instance, it's weird because it means `Spaceship::Members.find(Spaceship::Tunes.client.user)` is returning `nil`. Are you sure the email you're using is an `admin` in iTunes Connect (check itunesconnect.apple.com)? I've had a problem in the past where I thought I was an admin, but it turned out I was just an admin in the iTunes Developer portal, but not iTunes Connect.

**Comment by taquitos** [comment] 2017-06-26 22:41
@eskerber could you open up an issue with the problems you're facing? Being an app manager should work too 👍

**Comment by eskerber** [comment] 2017-06-27 01:04
@taquitos Yup (though isn't this issue the same thing?). You are right, I debugged a bit and that method was returning `nil` _only_ for my main account which happens to be an admin (technically - admin _and_ legal. Is that a problem?). Didn't have time to dig deep into Spaceship to see what was really happening.

It was resolved by using a dummy account with a regular app manager problem.

When I reported the problem earlier about an app manager not working, I admit that was a co-worker entering his creds in for me so I can't reproduce on a whim. I was able to get everything working using my own dummy app-manager account.

**Comment by taquitos** [comment] 2017-06-27 15:13
> admin and legal. Is that a problem?

That should be fine @eskerber, I'll see if I can repro. If I find anything weird with this combo I'll follow up in a different issue and @ you. Being `nil` could be a few different things, I'd still like to see if @RPasecky finds anything new about their account, so I'll leave this issue open.

**Comment by chadyj** [comment] 2018-01-15 15:26
I also came across this error and can reliably reproduce. Seems role/user related.

I have tested this with 2 different accounts. 
* Account 1 has roles `App Manager, Customer Support, Sales` and works fine
* Account 2 has role `App Manager` and shows the error `#<NoMethodError: undefined method `admin?' for nil:NilClass>`

@taquitos I'm happy to help debug this further.

**Comment by chadyj** [comment] 2018-01-16 02:28
I discovered the problem for me. Turns out that email address used for the ITC_USER environmental variable had capitals in it, and the ITC email needed to be all lowercase.

`Spaceship::Members.find("AB@gmail.com")` returned nil, but
`Spaceship::Members.find("ab@gmail.com")` worked.

**Comment by taquitos** [comment] 2018-04-04 06:26
@RPasecky that's awesome! Thanks for trying it out and getting back to us. We don't have anything more for ya to try out 🎉

**Closed by taquitos** 2018-04-04 06:26 UTC
