### ISSUE TITLE
Registration error since the new version of iTunes connect

### ISSUE THREAD

**Issue by andessa** [fastlane/boarding#126] opened 2017-04-12 15:03 UTC
it seems that Heroku isn't compatible with the new version of iTunes connect. 

![image](https://cloud.githubusercontent.com/assets/27359398/24964560/edd83dde-1fa1-11e7-9437-aa3a55a53d57.png)

Does someone found a solution ?

**Comment by mssun** [comment] 2017-04-12 15:55
Same issue for me.

**Comment by Phoenix7351** [comment] 2017-04-12 16:53
Same here.

**Comment by KrauseFx** [comment] 2017-04-12 22:51
We're working on a new version, you can follow the progress over here: https://github.com/fastlane/fastlane/pull/8871

Unfortunately there is a bug on iTunes Connect we have to wait for until we can ship 👍

**Comment by TonyZPW** [comment] 2017-04-13 05:46
Same, I need boarding very much now~...

**Comment by phonggenix** [comment] 2017-04-14 15:59
Same here.

**Comment by KrauseFx** [comment] 2017-04-14 16:37
Thanks everyone, please subscribe to https://github.com/fastlane/fastlane/pull/8871 to stay up to date on a fix 👍

**Comment by plaetzchen** [comment] 2017-04-20 17:01
So fastlane/fastlane#8871 is merged. Does this mean this should be fixed soon?

**Comment by rmoriz** [comment] 2017-04-20 18:10
I've manually updated the Gemfile.lock to get the new `fastlane` gem in, however:

 ```#<RuntimeError: `[tester].add_to_app!` got removed from spaceship as the TestFlight API changed, please use `app.default_external_group.add_tester!(tester)` instead>```

caused by https://github.com/fastlane/boarding/blob/41fb6571d461f13ce97209455250c1f8beb1d20f/app/controllers/invite_controller.rb#L94

**Comment by hengdaxiaofinnair** [comment] 2017-04-21 19:00
Depoly

**Comment by hengdaxiaofinnair** [comment] 2017-04-21 19:01
Deploy the latest the version to heroku, but when try to add the test user. Get this error

#<NoMethodError: undefined method `add_tester!' for nil:NilClass>

Some clue?

**Comment by skalee** [comment] 2017-04-21 19:59
@hengdaxiaofinnair Sure. No default external group. I don't know whether it's Boarding issue or configuration issue.

**Comment by KiminRyu** [comment] 2017-04-22 07:50
I got this error when I tried to register external tester. Attachment for log in heroku.

2017-04-22T07:45:07.202687+00:00 app[web.1]: Found tester 
2017-04-22T07:45:07.257045+00:00 app[web.1]: #<Faraday::SSLError wrapped=#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: tlsv1 unrecognized name>>
2017-04-22T07:45:07.257109+00:00 app[web.1]: /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/net/http.rb:923:in `connect'
2017-04-22T07:45:07.257110+00:00 app[web.1]: /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
2017-04-22T07:45:07.257111+00:00 app[web.1]: /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'

**Comment by skalee** [comment] 2017-04-22 22:17
@hengdaxiaofinnair @KiminRyu try #130.

**Comment by hengdaxiaofinnair** [comment] 2017-04-23 15:49
@skalee Thanks. Seems like works

**Comment by ogezue** [comment] 2017-04-24 09:32
Which steps are necessary to make it working with heroic again?
Deployed today but still getting error after registration.

**Comment by ogezue** [comment] 2017-04-24 15:26
I suppose this is not possible with the heroku-one-click installation?

**Comment by plaetzchen** [comment] 2017-04-24 15:35
@ogezue It is but you will need to do the following (see README):

- Clone from Heroku git
- Pull master
- Pull in the pull request ([see here](https://help.github.com/articles/checking-out-pull-requests-locally/))
- `git merge <the-branch>`
- `git push`

**Comment by ogezue** [comment] 2017-04-24 15:48
Thanks! Will try this. Hopefully @KrauseFx will merge soon.

**Comment by ogezue** [comment] 2017-04-26 07:09
@plaetzchen ?'m having problems merging your pull request locally. The syntax I assumed is wrong 
` git fetch origin pull/130/head:arbitrary-groups`

Can you help please?

**Comment by plaetzchen** [comment] 2017-04-26 07:59
@ogezue It's not mine but I can help.
This is what I did:

1. Git clone from Heroku
2. `git remote add origin https://github.com/fastlane/boarding.git`
3. `git fetch origin pull/130/head:arbitrary-groups`
4. `git checkout arbitrary-groups`
5. `git merge master`
6. `git checkout master`
7. `git merge arbitrary-groups`
8. `git push heroku master`
9. Set ENV variable on Heroku under Settings

**Comment by ogezue** [comment] 2017-04-26 08:14
Thank you so much! I executed the steps above, added an ENV variable with value 'myTestGroup' that I have created in ITC, restarted all dynos but the error message remains the same. Do you know what could be the problem?

**Comment by plaetzchen** [comment] 2017-04-26 08:31
OK can you install the heroku CLI tools and run heroku <instance> logs after testing it and post it here? May that's gives us an idea

**Comment by ogezue** [comment] 2017-04-26 09:10
I think that's it: 
`2017-04-26T08:29:12.434199+00:00 app[web.1]: Found tester 
2017-04-26T08:29:12.699486+00:00 app[web.1]: #<Spaceship::Client::InsufficientPermissions: User testaccount@testcompany.com (Team ID 123456) doesn't have enough permission for the following action: parse_response>
2017-04-26T08:29:12.699631+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/client.rb:574:in `raise_insuffient_permission_error!'
`
I have an itc user with the right to add testers (nothing more) because my admin password shouldn't be written to a third party. Is this the problem?

**Comment by plaetzchen** [comment] 2017-04-26 09:12
Right now boarding needs admin rights otherwise it will not work after the API changes. Maybe @KrauseFx can help to clarify why that is the case.

**Comment by ogezue** [comment] 2017-04-26 09:19
Yes! Now after granting admin rights I can confirm that it is working! 

Thank your very much!

**Comment by ogezue** [comment] 2017-04-26 09:27
Perhaps one remark: I was expecting that the user was added to the group I specified with the ENV variable. Instead it was added to the default group.

**Comment by taquitos** [comment] 2017-04-26 18:13
A fix for this has been merged, along with a significant refactor.
Check out https://github.com/fastlane/boarding/pull/135 for details, you can set ```ITC_APP_TESTER_GROUPS="group 1, group 2"```

There are a bunch of added startup checks too, so you can know if everything is configured correctly before loading the page.

Let me know if you have any questions, otherwise I think we can close this issue.

**Comment by TonyZPW** [comment] 2017-04-27 02:03
@taquitos thank you~ it works perfect~

**Closed** 2017-04-27 15:57 UTC
